name: Generate PDF
on:
  push:

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install texlive and extras
        run: sudo apt install texlive-xetex texlive-fonts-extra texlive-pstricks
      - name: Build pdf
        run: xelatex template.tex
      - name: Move the file tor resume.pdf
        run: mv template.pdf resume.pdf
      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: pdf-file
          path: resume.pdf
